=== terlyukevichDmitry/05_JavaST_2019/task04/data/vouchers.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema"
        targetNamespace="http://www.training.by/vouchers"
        xmlns:tns="http://www.training.by/vouchers"
        elementFormDefault="qualified">

    <element name="vouchers">
        <complexType>
            <sequence>
                <element ref="tns:AllVouchers"
                         minOccurs="1" maxOccurs="16"/>
            </sequence>
        </complexType>
    </element>

    <complexType name="VoucherTypes">
        <sequence>
            <element name="type" type="string"/>
        </sequence>
    </complexType>

    <complexType name="Voucher">
        <complexContent>
            <extension base="tns:VoucherTypes">
                <sequence>
                    <element name="country" type="tns:CountryInEnglishLanguage"/>
                    <element name="numberDaysNights" type="positiveInteger"/>
                    <element name="transport" type="tns:Transport"/>
                    <element name="hotel-characteristics" type="tns:Characteristics"/>
                    <element name="cost" type="tns:Price"/>
                    <element name="data-start" type="string"/>
                    <element name="data-finish" type="string"/>
                </sequence>
                <attribute name="id" type="ID" use="required"/>
            </extension>
        </complexContent>
    </complexType>

    <simpleType name="CountryInEnglishLanguage">
        <restriction base="string">
            <pattern value="([a-zA-Z]+)"/>
        </restriction>
    </simpleType>

    <simpleType name="Transport">
        <restriction base="string">
            <enumeration value="plane"/>
            <enumeration value="car"/>
            <enumeration value="bus"/>
            <enumeration value="train"/>
            <enumeration value="ship"/>
        </restriction>
    </simpleType>

    <complexType name="Characteristics">
        <sequence>
            <element name="stars" type="tns:Stars"/>
            <element name="nutrition" type="tns:Nutrition"/>
            <element name="room" type="positiveInteger"/>
            <element name="TV" type="boolean"/>
            <element name="WI-FI" type="boolean"/>
            <element name="air-conditioning" type="boolean"/>
        </sequence>
    </complexType>

    <simpleType name="Stars">
        <restriction base="positiveInteger">
            <maxInclusive value="5"/>
        </restriction>
    </simpleType>

    <simpleType name="Nutrition">
        <restriction base="string">
            <enumeration value="BB"/>
            <enumeration value="HB"/>
            <enumeration value="AL"/>
        </restriction>
    </simpleType>

    <complexType name="Price">
        <simpleContent>
            <extension base="decimal">
                  <attribute name="currency" type="tns:Currency" use="optional"
                           default="EUR"/>
            </extension>
        </simpleContent>
    </complexType>

    <simpleType name="Currency">
        <restriction base="string">
            <enumeration value="EUR"/>
            <enumeration value="RUB"/>
            <enumeration value="BYN"/>
            <enumeration value="USD"/>
        </restriction>
    </simpleType>

    <element name="AllVouchers" type="tns:VoucherTypes" abstract="true"/>
    <element name="voucher" type="tns:Voucher"
             substitutionGroup="tns:AllVouchers"/>
</schema>

=== terlyukevichDmitry/05_JavaST_2019/task04/data/vouchers.xml
<?xml version="1.0" encoding="UTF-8"?>
<vouchers xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
          xmlns="http://www.training.by/vouchers"
          xsi:schemaLocation="http://www.training.by/vouchers vouchers.xsd">
    <voucher id="first">
        <type>weekend</type>
        <country>Egypt</country>
        <numberDaysNights>10</numberDaysNights>
        <transport>plane</transport>
        <hotel-characteristics>
            <stars>5</stars>
            <nutrition>AL</nutrition>
            <room>2</room>
            <TV>true</TV>
            <WI-FI>true</WI-FI>
            <air-conditioning>true</air-conditioning>
        </hotel-characteristics>
        <cost currency="USD">1000</cost>
        <data-start>18.04.2019</data-start>
        <data-finish>28.04.2019</data-finish>
    </voucher>
</vouchers>
        <!--<element name="weekend" type="string"/>-->
        <!--<element name="relaxation" type="string"/>-->
        <!--<element name="excursion" type="string"/>-->
        <!--<element name="pilgrimage" type="string"/>-->
